version: "3.4"
services:
  mc_server:
    container_name: blightfall_server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EULA: true
        MODPACK_VERSION: 3.1.1
    ports:
      - '25565:25565'
      - '25575:25575'
      - '8123:8123'
    expose:
      - 25565
      - 25575
      - 8123
    tty: false
